const CONFIG = { url: 'https://pxzerharmpbxvmuomsfo.supabase.co', anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXAiLCJyZWYiOiJweHplcmhhcm1wYnh2bXVvbXNmbyIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzkwODQwLCJleHAiOjIxMDY0MTYyNDh9.9O5gSipGaZ66XSnp9FjI9tkIvcir3XZnvp6JBNyPV4A' };
CONFIG.anonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXAiLCJyZWYiOiJweHplcmhhcm1wYnh2bXVvbXNmbyIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzkwODQwLCJleHAiOjIxMDY0MTYyNDh9.9O5gSipGaZ66XSnp9FjI9tkIvcir3XZnvp6JBNyPV4A';
const $ = id => document.getElementById(id); let dbClient = null, userId = null, archive = [];
const key = () => `tailframe-drama-archive:${userId || 'signed-out'}`;
const local = () => { try { const x = JSON.parse(localStorage.getItem(key()) || '[]'); return Array.isArray(x) ? x : []; } catch { return []; } };
const sync = (m, yes=false) => { $('sync-status').textContent=m; $('sync-status').parentElement.classList.toggle('online',yes); };
function render(){ $('archive-count').textContent=archive.length; const root=$('archive-list'); root.innerHTML=''; if(!archive.length){root.innerHTML='<p class="empty">아직 보관한 드라마가 없습니다.</p>';return;} const t=$('archive-item'); archive.forEach(item=>{const n=t.content.cloneNode(true);n.querySelector('h3').textContent=item.title;n.querySelector('.archive-meta').textContent=new Date(item.created_at||Date.now()).toLocaleString('ko-KR');n.querySelector('.archive-summary').textContent=item.summary||'';n.querySelector('.view').onclick=()=>{localStorage.setItem('tailframe-opened-drama',JSON.stringify(item));location.href='drama.html?opened=archive';};n.querySelector('.remove').onclick=()=>remove(item);root.append(n);});}
async function load(){if(!dbClient||!userId){archive=local();render();return;}const {data,error}=await dbClient.from('drama_archive').select('*').order('created_at',{ascending:false});if(error){sync('PC 드라마 보관함 사용 중');archive=local();render();return;}archive=[...(data||[]),...local().filter(l=>!(data||[]).some(c=>c.signature===l.signature))];render();}
async function remove(item){if(!confirm('이 드라마와 중복 방지 이력을 삭제할까요?'))return;localStorage.setItem(key(),JSON.stringify(local().filter(x=>x.id!==item.id&&x.signature!==item.signature)));if(item.user_id&&dbClient&&userId){const {error}=await dbClient.from('drama_archive').delete().eq('id',item.id);if(error)return alert(`삭제하지 못했습니다: ${error.message}`);}await load();}
$('refresh').onclick=load; window.connectSupabase=async()=>{try{dbClient=window.supabase.createClient(CONFIG.url,CONFIG.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});const {data:{session}}=await dbClient.auth.getSession();userId=session?.user?.is_anonymous?null:session?.user?.id;if(!userId){sync('PC 드라마 보관함 사용 중');return load();}sync('Supabase 드라마 보관함 연결됨',true);await load();}catch{sync('PC 드라마 보관함 사용 중');await load();}};load();
