using System; using System.Collections.Generic; using System.Drawing; using System.IO; using System.Linq; using System.Text; using System.Windows.Forms;
internal static class CreatureAnimationStudio {
 [STAThread] static void Main(){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new App());}
 sealed class Room { public string Id,Name,Photo,Theme; public override string ToString(){return Name;} }
 sealed class Item { public string Title,Key,Text; public override string ToString(){return Title;} }
 sealed class App:Form {
  readonly string root=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"CreatureAnimationStudio"); readonly List<Room> rooms=new List<Room>(); readonly Random r=new Random();
  readonly string[] places={"a miniature omakase bar","a cozy magical bakery","a moonlit flower garden","a sparkling seaside market","a tiny fantasy kitchen"}; readonly string[] props={"a jewel-like strawberry parfait","a glowing teacup","a rainbow cake","a cloud-shaped mochi","a crystal fruit basket"}; readonly string[] actions={"discovers","carefully investigates","tries to prepare","gently tastes","plays with"}; readonly string[] endings={"does a happy spin","waves toward the camera","tilts its head with delight","makes a gentle final jump"};
  Panel page; Room current; ListBox roomList,archive; TextBox theme,result; PictureBox photo; Label photoLabel;
  public App(){Directory.CreateDirectory(root);Text="Creature Animation Prompt Studio";Size=new Size(1220,790);MinimumSize=new Size(900,620);BackColor=Color.FromArgb(246,249,253);Font=new Font("Malgun Gothic",10);LoadRooms();ShowHome();}
  string RoomsFile{get{return Path.Combine(root,"rooms.dat");}} string ArchiveFile{get{return Path.Combine(root,"archive-"+current.Id+".dat");}} string E(string s){return Convert.ToBase64String(Encoding.UTF8.GetBytes(s??""));} string D(string s){try{return Encoding.UTF8.GetString(Convert.FromBase64String(s));}catch{return "";}}
  void LoadRooms(){if(File.Exists(RoomsFile))foreach(var x in File.ReadAllLines(RoomsFile)){var p=x.Split('|');if(p.Length==4)rooms.Add(new Room{Id=p[0],Name=D(p[1]),Photo=D(p[2]),Theme=D(p[3])});}}
  void SaveRooms(){File.WriteAllLines(RoomsFile,rooms.Select(x=>x.Id+"|"+E(x.Name)+"|"+E(x.Photo)+"|"+E(x.Theme)));}
  void SetPage(Control c){if(page!=null)Controls.Remove(page);page=new Panel{Dock=DockStyle.Fill,Padding=new Padding(32),BackColor=BackColor};page.Controls.Add(c);Controls.Add(page);}
  Label Title(string s){return new Label{Text=s,Dock=DockStyle.Top,Height=55,Font=new Font("Malgun Gothic",20,FontStyle.Bold),ForeColor=Color.FromArgb(30,55,83)};} Button Btn(string s,Action a,bool main=false){var b=new Button{Text=s,Height=42,FlatStyle=FlatStyle.Flat,BackColor=main?Color.FromArgb(45,174,160):Color.White,ForeColor=main?Color.White:Color.FromArgb(40,78,118),Font=new Font("Malgun Gothic",9,FontStyle.Bold)};b.FlatAppearance.BorderColor=main?b.BackColor:Color.FromArgb(190,210,230);b.Click+=(o,e)=>a();return b;}
  void ShowHome(){var wrap=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=3};wrap.RowStyles.Add(new RowStyle(SizeType.Absolute,85));wrap.RowStyles.Add(new RowStyle(SizeType.Percent,100));wrap.RowStyles.Add(new RowStyle(SizeType.Absolute,55));wrap.Controls.Add(Title("작업실"),0,0);var listCard=Card();roomList=new ListBox{Dock=DockStyle.Fill,Font=new Font("Malgun Gothic",11),BorderStyle=BorderStyle.None};roomList.Items.AddRange(rooms.Cast<object>().ToArray());roomList.DoubleClick+=(s,e)=>OpenSelected();listCard.Controls.Add(roomList);wrap.Controls.Add(listCard,0,1);var buttons=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.LeftToRight};var create=Btn("+ 작업실 생성",CreateRoom,true);create.Width=160;var open=Btn("작업실 입장",OpenSelected);open.Width=140;buttons.Controls.Add(create);buttons.Controls.Add(open);wrap.Controls.Add(buttons,0,2);SetPage(wrap);}
  Panel Card(){return new Panel{Dock=DockStyle.Fill,BackColor=Color.White,Padding=new Padding(16),BorderStyle=BorderStyle.FixedSingle};}
  void CreateRoom(){var n=Microsoft.VisualBasic.Interaction.InputBox("작업실 이름을 입력하세요.","작업실 생성","");if(String.IsNullOrWhiteSpace(n))return;var room=new Room{Id=Guid.NewGuid().ToString("N"),Name=n.Trim(),Theme="이 캐릭터가 주제에 맞게 움직이는 고품질 TikTok 3D 애니메이션",Photo=""};rooms.Add(room);SaveRooms();current=room;ShowWorkspace();}
  void OpenSelected(){var x=roomList==null?null:roomList.SelectedItem as Room;if(x==null){MessageBox.Show("입장할 작업실을 선택하세요.");return;}current=x;ShowWorkspace();}
  void ShowWorkspace(){var all=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RowCount=2};all.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,290));all.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));all.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,245));all.RowStyles.Add(new RowStyle(SizeType.Absolute,66));all.RowStyles.Add(new RowStyle(SizeType.Percent,100));var back=Btn("← 작업실 목록",ShowHome);back.Width=130;var head=new FlowLayoutPanel{Dock=DockStyle.Fill};head.Controls.Add(back);head.Controls.Add(new Label{Text=current.Name,AutoSize=true,Margin=new Padding(20,9,0,0),Font=new Font("Malgun Gothic",17,FontStyle.Bold),ForeColor=Color.FromArgb(30,55,83)});all.SetColumnSpan(head,3);all.Controls.Add(head,0,0);all.Controls.Add(Settings(),0,1);all.Controls.Add(Result(),1,1);all.Controls.Add(Archive(),2,1);SetPage(all);}
  Control Settings(){var c=Card();var f=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true};f.Controls.Add(L("캐릭터 기준 사진"));photo=new PictureBox{Size=new Size(230,150),SizeMode=PictureBoxSizeMode.Zoom,BackColor=Color.FromArgb(242,246,250)};f.Controls.Add(photo);photoLabel=new Label{Width=240,Height=25,ForeColor=Color.FromArgb(100,116,139)};f.Controls.Add(photoLabel);var attach=Btn("사진 첨부",Attach);attach.Width=230;f.Controls.Add(attach);f.Controls.Add(L("작업실 주제"));theme=new TextBox{Multiline=true,Width=230,Height=110,Text=current.Theme,BackColor=Color.FromArgb(250,252,255)};f.Controls.Add(theme);var save=Btn("작업실 설정 저장",SaveCurrent);save.Width=230;f.Controls.Add(save);var gen=Btn("완성 프롬프트 만들기",Generate,true);gen.Width=230;f.Controls.Add(gen);LoadPhoto();c.Controls.Add(f);return c;}
  Label L(string x){return new Label{Text=x,Width=235,Height=26,Margin=new Padding(0,8,0,1),Font=new Font("Malgun Gothic",9,FontStyle.Bold),ForeColor=Color.FromArgb(51,65,85)};}
  void LoadPhoto(){photo.Image=null;photoLabel.Text=String.IsNullOrWhiteSpace(current.Photo)?"사진을 첨부해 주세요":Path.GetFileName(current.Photo);if(File.Exists(current.Photo))try{photo.Image=Image.FromFile(current.Photo);}catch{}}
  void Attach(){using(var d=new OpenFileDialog{Title="이 작업실의 캐릭터 기준 사진",Filter="이미지 파일|*.png;*.jpg;*.jpeg;*.webp"}){if(d.ShowDialog()!=DialogResult.OK)return;current.Photo=d.FileName;SaveRooms();LoadPhoto();}}
  void SaveCurrent(){current.Theme=theme.Text.Trim();SaveRooms();}
  Control Result(){var c=Card();var copy=Btn("영상 · BGM · 효과음 전체 복사",()=>{if(result.TextLength>0)Clipboard.SetText(result.Text);});copy.Dock=DockStyle.Top;c.Controls.Add(copy);c.Controls.Add(new Label{Text="완성 프롬프트 · 직접 수정 가능",Dock=DockStyle.Top,Height=30,Font=new Font("Malgun Gothic",11,FontStyle.Bold)});result=new TextBox{Dock=DockStyle.Fill,Multiline=true,ScrollBars=ScrollBars.Vertical,Font=new Font("Consolas",9),BackColor=Color.FromArgb(250,252,255),BorderStyle=BorderStyle.FixedSingle};c.Controls.Add(result);return c;}
  Control Archive(){var c=Card();var del=Btn("선택 제작물 삭제",DeleteArchive);del.Dock=DockStyle.Bottom;c.Controls.Add(del);var update=Btn("수정 내용 저장",UpdateArchive);update.Dock=DockStyle.Bottom;c.Controls.Add(update);c.Controls.Add(new Label{Text="보관함",Dock=DockStyle.Top,Height=30,Font=new Font("Malgun Gothic",11,FontStyle.Bold)});archive=new ListBox{Dock=DockStyle.Fill,BorderStyle=BorderStyle.None};archive.DoubleClick+=(s,e)=>{var x=archive.SelectedItem as Item;if(x!=null)result.Text=x.Text;};c.Controls.Add(archive);LoadArchive();return c;}
  List<Item> GetArchive(){if(!File.Exists(ArchiveFile))return new List<Item>();return File.ReadAllLines(ArchiveFile).Select(x=>{var p=x.Split('|');return p.Length==3?new Item{Title=D(p[0]),Key=D(p[1]),Text=D(p[2])}:null;}).Where(x=>x!=null).ToList();}
  void LoadArchive(){if(archive==null)return;archive.Items.Clear();archive.Items.AddRange(GetArchive().Cast<object>().ToArray());}
  void DeleteArchive(){var x=archive.SelectedItem as Item;if(x==null)return;if(MessageBox.Show("선택한 제작물을 보관함에서 삭제할까요?","삭제",MessageBoxButtons.YesNo)==DialogResult.Yes){var left=GetArchive().Where(i=>i.Title!=x.Title).Select(i=>E(i.Title)+"|"+E(i.Key)+"|"+E(i.Text));File.WriteAllLines(ArchiveFile,left);LoadArchive();}}
  void UpdateArchive(){var x=archive.SelectedItem as Item;if(x==null||String.IsNullOrWhiteSpace(result.Text)){MessageBox.Show("보관함에서 수정할 제작물을 선택하세요.");return;}var all=GetArchive();var found=all.First(i=>i.Title==x.Title);found.Text=result.Text;File.WriteAllLines(ArchiveFile,all.Select(i=>E(i.Title)+"|"+E(i.Key)+"|"+E(i.Text)));LoadArchive();MessageBox.Show("수정 내용을 저장했습니다.");}
  string Pick(string[] a){return a[r.Next(a.Length)];}
  void Generate(){SaveCurrent();if(String.IsNullOrWhiteSpace(current.Photo)){MessageBox.Show("먼저 캐릭터 기준 사진을 첨부하세요.");return;}var used=GetArchive().Select(x=>x.Key).ToHashSet();string place,prop,act,key;int n=0;do{place=Pick(places);prop=Pick(props);act=Pick(actions);key=place+"/"+prop+"/"+act;n++;}while(used.Contains(key)&&n<50);var title=current.Name+" — "+prop+" 이야기";var story=current.Theme;result.Text="[이번 영상]\r\n제목 : "+title+"\r\n소개글 : "+story+" 속에서 첨부 캐릭터가 "+prop+"을(를) "+act+" 4장면 TikTok 3D 애니메이션.\r\nKEY: "+key+"\r\n\r\n[공통 캐릭터 고정 프롬프트]\r\nUse only the character from the attached reference image as the protagonist in every scene. Preserve exact face, proportions, colors, defining features and identity. High-end stylized 3D animation, vertical 9:16, consistent character model, lighting and environment.\r\n\r\n[장면 1 — 발견]\r\nImage/video prompt: In "+place+", the attached-reference character "+act+" "+prop+". Establish the theme: "+story+". Medium cinematic shot, curious expression, no cut.\r\nMotion & camera: natural approach, stable camera axis.\r\nSound: subtle location ambience, small character reaction, light BGM start.\r\n\r\n[장면 2 — 상호작용]\r\nImage/video prompt: Continue seamlessly in the same setting. The identical character interacts physically with the same "+prop+"; preserve its position and state. Close-up on expression and contact.\r\nMotion & camera: smooth push-in, readable tactile action.\r\nSound: synchronized ASMR/contact effects, gentle character sound.\r\n\r\n[장면 3 — 주제 전개]\r\nImage/video prompt: The story develops into the core moment of: "+story+". Keep the identical character, prop, location and direction. Add only theme-relevant magical/environment detail.\r\nMotion & camera: follow the action without jump cuts.\r\nSound: themed effects rise naturally; music builds.\r\n\r\n[장면 4 — 엔딩]\r\nImage/video prompt: Resolve the same story in the same environment. The attached-reference character "+Pick(endings)+", clearly showing the completed theme moment and "+prop+". Premium loopable TikTok ending, clean composition, no text.\r\nMotion & camera: graceful small pullback and final hold.\r\nSound: warm final character sound, soft resolving effect.\r\n\r\n[BGM · 효과음]\r\nOne continuous bright, cute, cinematic instrumental BGM with no vocals. Start curious, become playful during interaction, build at the core moment, resolve warmly. Keep music beneath synchronized character and prop effects.\r\n\r\n[공통 네거티브 프롬프트]\r\ndifferent character, inconsistent face, character redesign, extra characters, human hands, inconsistent prop, teleportation, sudden environment change, jump cut, malformed anatomy, horror, gore, text, subtitles, logo, watermark, UI.";}
  void SaveArchive(){if(result==null||String.IsNullOrWhiteSpace(result.Text))return;var title=Read("제목 :");var key=Read("KEY:");File.AppendAllText(ArchiveFile,E(title)+"|"+E(key)+"|"+E(result.Text)+Environment.NewLine);LoadArchive();}
  string Read(string k){var i=result.Text.IndexOf(k);if(i<0)return DateTime.Now.ToString("yyyy-MM-dd HH:mm");var e=result.Text.IndexOf('\n',i);return result.Text.Substring(i+k.Length,(e<0?result.Text.Length:e)-i-k.Length).Trim();}
 }
}
